// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACd09yOn3EU_gOIIZso4eSUfkR8u4qT3s',
    appId: '1:903745139754:web:98c9e9aea453b6be86ff53',
    messagingSenderId: '903745139754',
    projectId: 'event-hall-booking-b6acb',
    authDomain: 'event-hall-booking-b6acb.firebaseapp.com',
    storageBucket: 'event-hall-booking-b6acb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBycCem_9Tom7O-K_D4sQvz4UZWD8jcSUg',
    appId: '1:903745139754:android:a8edbed445a6508f86ff53',
    messagingSenderId: '903745139754',
    projectId: 'event-hall-booking-b6acb',
    storageBucket: 'event-hall-booking-b6acb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6MZg4N96_h1JWuThbGdhGRpN2muxpz6o',
    appId: '1:903745139754:ios:be21545ced810f8e86ff53',
    messagingSenderId: '903745139754',
    projectId: 'event-hall-booking-b6acb',
    storageBucket: 'event-hall-booking-b6acb.firebasestorage.app',
    iosBundleId: 'com.example.venue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6MZg4N96_h1JWuThbGdhGRpN2muxpz6o',
    appId: '1:903745139754:ios:be21545ced810f8e86ff53',
    messagingSenderId: '903745139754',
    projectId: 'event-hall-booking-b6acb',
    storageBucket: 'event-hall-booking-b6acb.firebasestorage.app',
    iosBundleId: 'com.example.venue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACd09yOn3EU_gOIIZso4eSUfkR8u4qT3s',
    appId: '1:903745139754:web:db536435751b11e986ff53',
    messagingSenderId: '903745139754',
    projectId: 'event-hall-booking-b6acb',
    authDomain: 'event-hall-booking-b6acb.firebaseapp.com',
    storageBucket: 'event-hall-booking-b6acb.firebasestorage.app',
  );
}
